### ISSUE TITLE
add test and/or demo data

### ISSUE THREAD

**Issue by herbstk** [ilia-kats/imisc#6]
Maybe just use one of the generic dataset from Rbase which has the respective factorization (strain, replicate...). It would also be nice to have one dataset as usecase for each proposed function or for each function one simple dataset.

**Comment by ilia-kats** [comment]
There are a couple of basic examples in the documentation now, feel 
free to add more

**Comment by ilia-kats** [comment]
the functionality should be now extensively documented in the unit tests (with output examples in the tests/figs directory). closing the issue
